export const brandsList = [
  {
    brandId: 113,
    brandDescEN: "AASHIRVAAD",
    imagePath: "AASHIRVAAD.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 97,
    brandDescEN: "ACT II",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 386,
    brandDescEN: "AER",
    imagePath: "Aer.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 338,
    brandDescEN: "ALL OUT",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 216,
    brandDescEN: "BAJAJ",
    imagePath: "Bajaj.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 301,
    brandDescEN: "BIC CELLO",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 104,
    brandDescEN: "BINGO",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 811,
    brandDescEN: "BIOTIQUE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1707,
    brandDescEN: "BOLAS",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 354,
    brandDescEN: "BORO PLUS",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 133,
    brandDescEN: "BOURNVITA",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1112,
    brandDescEN: "BROWN & POLSON",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 409,
    brandDescEN: "CAMPA",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 199,
    brandDescEN: "CHIK",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 120,
    brandDescEN: "CHINGS SECRET",
    imagePath: "CHINGS-SECRET.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 60,
    brandDescEN: "CINTHOL",
    imagePath: "Cinthol.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 388,
    brandDescEN: "CLEAN & CLEAR",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 173,
    brandDescEN: "CLINIC PLUS",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 169,
    brandDescEN: "CLOSEUP",
    imagePath: "Closeup.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 219,
    brandDescEN: "COCA COLA",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 164,
    brandDescEN: "COLGATE",
    imagePath: "Colgate.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 165,
    brandDescEN: "COLGATE PALMOLIVE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 223,
    brandDescEN: "COMPLAN",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 86,
    brandDescEN: "DABUR",
    imagePath: "Dabur.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1079,
    brandDescEN: "DENVER",
    imagePath: "Denver.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 584,
    brandDescEN: "DERMICOOL",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 9,
    brandDescEN: "DETTOL",
    imagePath: "Dettol.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 42,
    brandDescEN: "DOMS",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1378,
    brandDescEN: "DOUBLE CHABI",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 176,
    brandDescEN: "DOVE",
    imagePath: "Dove.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 319,
    brandDescEN: "DURACELL",
    imagePath: "Duracell.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 459,
    brandDescEN: "ENO",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 2,
    brandDescEN: "ENZO",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 73,
    brandDescEN: "EVEREADY",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 32,
    brandDescEN: "EVEREST",
    imagePath: "Everest.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 356,
    brandDescEN: "FAIR & LOVELY",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 220,
    brandDescEN: "FANTA",
    imagePath: "Fanta.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 58,
    brandDescEN: "FLAIR",
    imagePath: "Flair.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1068,
    brandDescEN: "FOGG",
    imagePath: "Fogg.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 115,
    brandDescEN: "FORTUNE",
    imagePath: "Fortune.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 71,
    brandDescEN: "GALA",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 226,
    brandDescEN: "GARNIER",
    imagePath: "Garnier.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 345,
    brandDescEN: "GLOW & LOVELY",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 180,
    brandDescEN: "GODREJ",
    imagePath: "Godrej.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1348,
    brandDescEN: "GODREJ EXPERT",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 46,
    brandDescEN: "GOOD KNIGHT",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1746,
    brandDescEN: "GOOD LIFE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 163,
    brandDescEN: "HAIR & CARE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1059,
    brandDescEN: "HAMAM",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 20,
    brandDescEN: "HAUSER",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 212,
    brandDescEN: "HEAD & SHOULDERS",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 202,
    brandDescEN: "HIMALAYA",
    imagePath: "Himalaya.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 17,
    brandDescEN: "HORLICKS",
    imagePath: "HORLICKS.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1,
    brandDescEN: "INDEPENDENCE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 201,
    brandDescEN: "INDICA",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 843,
    brandDescEN: "INDULEKHA",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 37,
    brandDescEN: "IODEX",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 158,
    brandDescEN: "JOHNSONS",
    imagePath: "Johnsons.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 336,
    brandDescEN: "KAMASUTRA",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 149,
    brandDescEN: "KINLEY",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 123,
    brandDescEN: "KISSAN",
    imagePath: "Kissan.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1074,
    brandDescEN: "KRACKJACK",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 547,
    brandDescEN: "KUMUD",
    imagePath: "Kumud.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 124,
    brandDescEN: "KURKURE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 177,
    brandDescEN: "LAKME",
    imagePath: "Lakme.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 290,
    brandDescEN: "LIFEBUOY",
    imagePath: "Lifebuoy.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 614,
    brandDescEN: "LINC",
    imagePath: "Linc.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 264,
    brandDescEN: "LIRIL",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 93,
    brandDescEN: "LOOSE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 261,
    brandDescEN: "LOREAL PARIS",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 178,
    brandDescEN: "LUX",
    imagePath: "Lux.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 106,
    brandDescEN: "M-SEAL",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1476,
    brandDescEN: "M.P. GOLD",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 98,
    brandDescEN: "MAGGI",
    imagePath: "Maggi.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 514,
    brandDescEN: "MAMAEARTH",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 872,
    brandDescEN: "MANGALAM",
    imagePath: "Mangalam.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 248,
    brandDescEN: "MANGALDEEP",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1431,
    brandDescEN: "MOLSIS",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1095,
    brandDescEN: "MOMS MAGIC",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 366,
    brandDescEN: "MONACO",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1106,
    brandDescEN: "MONSTER",
    imagePath: "Monster.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1749,
    brandDescEN: "MOTHERS RECIPE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1750,
    brandDescEN: "NAVRATNA",
    imagePath: "Navratna.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 138,
    brandDescEN: "NESCAFE",
    imagePath: "Nescafe.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 47,
    brandDescEN: "NESTLE",
    imagePath: "Nestle.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 161,
    brandDescEN: "NIHAR",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 372,
    brandDescEN: "OREO",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 296,
    brandDescEN: "PAMPERS",
    imagePath: "Pampers.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 213,
    brandDescEN: "PANTENE",
    imagePath: "PANTENE.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 159,
    brandDescEN: "PARACHUTE",
    imagePath: "Parachute.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 458,
    brandDescEN: "PAREE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 204,
    brandDescEN: "PARK AVENUE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 43,
    brandDescEN: "PARLE",
    imagePath: "Parle.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 367,
    brandDescEN: "PARLE 20-20",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 270,
    brandDescEN: "PARLE FAB",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 377,
    brandDescEN: "PARLE HAPPY HAPPY",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 384,
    brandDescEN: "PARLE HIDE & SEEK",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1120,
    brandDescEN: "PARLE MARIE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 179,
    brandDescEN: "PEARS",
    imagePath: "Pears.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 308,
    brandDescEN: "PEDIASURE",
    imagePath: "Pediasure.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 562,
    brandDescEN: "PENTONIC",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 171,
    brandDescEN: "PEPSODENT",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 291,
    brandDescEN: "PERK",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 175,
    brandDescEN: "PONDS",
    imagePath: "Ponds.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 94,
    brandDescEN: "PRIVATE LABEL",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 215,
    brandDescEN: "QUAKER",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 863,
    brandDescEN: "RASKIK",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 139,
    brandDescEN: "REAL",
    imagePath: "Real.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 107,
    brandDescEN: "RED BULL",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 140,
    brandDescEN: "RED LABEL",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 160,
    brandDescEN: "REVIVE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 99,
    brandDescEN: "RIN",
    imagePath: "Rin.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 96,
    brandDescEN: "SAFFOLA",
    imagePath: "Saffola.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 232,
    brandDescEN: "SANIFRESH",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 167,
    brandDescEN: "SANTOOR",
    imagePath: "Santoor.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1752,
    brandDescEN: "SAVLON",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 311,
    brandDescEN: "SENSODYNE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 391,
    brandDescEN: "SET WET",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1099,
    brandDescEN: "SNACTAC",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 350,
    brandDescEN: "SPINZ",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 221,
    brandDescEN: "SPRITE",
    imagePath: "Sprite.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 53,
    brandDescEN: "STAYFREE",
    imagePath: "Stayfree.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 241,
    brandDescEN: "SUGAR FREE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 38,
    brandDescEN: "SUNFEAST",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 26,
    brandDescEN: "SUNFEAST YIPPEE!",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 142,
    brandDescEN: "SUNRISE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 174,
    brandDescEN: "SUNSILK",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 88,
    brandDescEN: "SURF EXCEL",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 234,
    brandDescEN: "TAAZA",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 143,
    brandDescEN: "TAJ MAHAL",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 64,
    brandDescEN: "TATA",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 225,
    brandDescEN: "TATA AGNI",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 144,
    brandDescEN: "TATA GOLD",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 157,
    brandDescEN: "TATA PREMIUM",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 339,
    brandDescEN: "TATA SAMPANN",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 329,
    brandDescEN: "THUMS UP",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 597,
    brandDescEN: "TOPS",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 389,
    brandDescEN: "TRESEMME",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 127,
    brandDescEN: "UNCLE CHIPPS",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 207,
    brandDescEN: "VASELINE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 28,
    brandDescEN: "VIM",
    imagePath: "Vim.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 373,
    brandDescEN: "VIVEL",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 211,
    brandDescEN: "WHISPER",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 1414,
    brandDescEN: "WHITE TONE",
    imagePath: "",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
  {
    brandId: 353,
    brandDescEN: "ZANDU",
    imagePath: "Zandu.png",
    mrp: 12.0,
    jioMartPrice: 10.59,
    quantity: 0,
  },
];
